ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
#[kent][begin] verify t4k37 product information  
#obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o 
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o t4k37_otp.o ov5670_otp.o
#[kent][end] verify t4k37 product information  